### ISSUE TITLE
Peer reviews (16 april 2021)

### ISSUE THREAD

**Issue by RooyyDoe** [NathanNeelis/real-time-web-2021#1]
## Scan your buddy's repository

- Good project description! 👍 
- The demo is _ALIVE_
- No random files everything is just fine! 👍 
- What are you missing❓
   - You're missing the **External API** information   
   - You're also missing an explanation about the real-time events

## Try to understand the concept
- Concept seems pretty clear to me! 👍 
- Maybe you can add a screen in between the `/room` and `/playground` with the key to join, so that the creator can send it to his friends. 🔑 
- The way you made that grid is awesome! 💯  I also like that u used `localStorage` to remember the color/name! 👍  
- Maybe you can also add a user list of the users that are in the room.

## Understand the data life cycle
- Mainly what we talked about in the discord call. I like to put as much information in it as possible to defend myself in appreciation.
- If you want to use my Data Lifecycle as an example go ahead! 👍 

## Check the real-time events
- At the moment there are none 😭 

## review the API info
- There is no API information.

If you add anything new just message me and I will read it again.

**Comment by NathanNeelis** [comment]
### Scan your buddy's repository
* [x] DONE - You're missing the External API information
* [x] DONE - You're also missing an explanation about the real-time events
* [x] DONE - It's in the chatbox now- Maybe you can add a screen in between the /room and /playground with the key to join, so that the creator can send it to his friends. 
* [ ] TO DO - Maybe you can also add a user list of the users that are in the room.
> Was nice to have, ran out of time.
* [x]  DatalifeCycle Diagram - updated and finalised 
* [x]  DONE - Added some info about real-time events
* [x] DONE - Added some API info.

### Thanks for the feedback Roy!
